export const FORM_REPOSITORY = Symbol('FORM_REPOSITORY');
export const FORM_SUBMISSION_REPOSITORY = Symbol('FORM_SUBMISSION_REPOSITORY');
export const PAGE_TRANSLATION_REPOSITORY = Symbol(
  'FORMS_PAGE_TRANSLATION_REPOSITORY',
);
