export const REUSABLE_SECTION_REPOSITORY = Symbol(
  'REUSABLE_SECTION_REPOSITORY',
);
export const REUSABLE_SECTION_VERSION_REPOSITORY = Symbol(
  'REUSABLE_SECTION_VERSION_REPOSITORY',
);
export const PAGE_GROUP_REPOSITORY = Symbol('PAGE_GROUP_REPOSITORY');
export const PAGE_TRANSLATION_REPOSITORY = Symbol(
  'PAGE_TRANSLATION_REPOSITORY',
);
export const SEARCH_PORT = Symbol('SEARCH_PORT');
export const PREVIEW_TOKEN_PORT = Symbol('PREVIEW_TOKEN_PORT');
