export const SITE_LAYOUT_SECTION_REPOSITORY = Symbol(
  'SITE_LAYOUT_SECTION_REPOSITORY',
);
export const SITE_LAYOUT_SECTION_VERSION_REPOSITORY = Symbol(
  'SITE_LAYOUT_SECTION_VERSION_REPOSITORY',
);
export const SITE_REPOSITORY = Symbol('SITE_REPOSITORY');
export const PREVIEW_TOKEN_PORT = Symbol('PREVIEW_TOKEN_PORT');
