export const IMPORT_JOB_REPOSITORY = Symbol('IMPORT_JOB_REPOSITORY');
export const SITE_REPOSITORY = Symbol('IMPORTS_SITE_REPOSITORY');
export const WORDPRESS_EXPORT_READER = Symbol('WORDPRESS_EXPORT_READER');
