export const SEARCH_REPOSITORY = Symbol('SEARCH_REPOSITORY');
export const PREVIEW_TOKEN_PORT = Symbol('PREVIEW_TOKEN_PORT');
export const REUSABLE_SECTION_REPOSITORY = Symbol(
  'REUSABLE_SECTION_REPOSITORY',
);
export const TAXONOMY_REPOSITORY = Symbol('TAXONOMY_REPOSITORY');
export const SITE_REPOSITORY = Symbol('SITE_REPOSITORY');
export const COLLECTION_REPOSITORY = Symbol('COLLECTION_REPOSITORY');
