export const PAGE_GROUP_REPOSITORY = Symbol('PAGE_GROUP_REPOSITORY');
export const PAGE_GROUP_VERSION_REPOSITORY = Symbol(
  'PAGE_GROUP_VERSION_REPOSITORY',
);
export const PAGE_TRANSLATION_REPOSITORY = Symbol(
  'PAGE_TRANSLATION_REPOSITORY',
);
export const PAGE_TRANSLATION_VERSION_REPOSITORY = Symbol(
  'PAGE_TRANSLATION_VERSION_REPOSITORY',
);
