export const PAGE_REPOSITORY = Symbol('PAGE_REPOSITORY');
export const PAGE_VERSION_REPOSITORY = Symbol('PAGE_VERSION_REPOSITORY');
export const SEARCH_REPOSITORY = Symbol('SEARCH_REPOSITORY');
export const TENANT_CONTEXT = Symbol('TENANT_CONTEXT');
export const PREVIEW_TOKEN_PORT = Symbol('PREVIEW_TOKEN_PORT');
export const DEFAULT_TENANT_ID = Symbol('DEFAULT_TENANT_ID');
