export const SITE_LAYOUT_SECTION_REPOSITORY = Symbol(
  'PUBLIC_SITE_LAYOUT_SECTION_REPOSITORY',
);
export const PREVIEW_TOKEN_PORT = Symbol('PUBLIC_PREVIEW_TOKEN_PORT');
export const DEFAULT_TENANT_ID = Symbol('PUBLIC_DEFAULT_TENANT_ID');
