export const FORM_REPOSITORY = Symbol('PUBLIC_FORM_REPOSITORY');
export const FORM_SUBMISSION_REPOSITORY = Symbol(
  'PUBLIC_FORM_SUBMISSION_REPOSITORY',
);
export const EMAIL_PORT = Symbol('PUBLIC_FORMS_EMAIL_PORT');
export const CAPTCHA_PORT = Symbol('PUBLIC_FORMS_CAPTCHA_PORT');
export const NEWSLETTER_PORT = Symbol('PUBLIC_FORMS_NEWSLETTER_PORT');
export const ATTACHMENT_STORAGE = Symbol('PUBLIC_FORMS_ATTACHMENT_STORAGE');
export const DEFAULT_TENANT_ID = Symbol('PUBLIC_FORMS_DEFAULT_TENANT_ID');
