export const PAGE_GROUP_REPOSITORY = Symbol('PUBLIC_PAGE_GROUP_REPOSITORY');
export const PAGE_TRANSLATION_REPOSITORY = Symbol(
  'PUBLIC_PAGE_TRANSLATION_REPOSITORY',
);
export const SITE_REPOSITORY = Symbol('PUBLIC_SITE_REPOSITORY');
export const SITE_LAYOUT_SECTION_REPOSITORY = Symbol(
  'PUBLIC_SITE_LAYOUT_SECTION_REPOSITORY',
);
export const SITE_THEME_BLOCK_STYLES_REPOSITORY = Symbol(
  'PUBLIC_SITE_THEME_BLOCK_STYLES_REPOSITORY',
);
export const SEARCH_REPOSITORY = Symbol('PUBLIC_SEARCH_REPOSITORY');
export const DEFAULT_TENANT_ID = Symbol('PUBLIC_DEFAULT_TENANT_ID');
export const PREVIEW_TOKEN_PORT = Symbol('PUBLIC_PREVIEW_TOKEN_PORT');
