export const PAGE_REPOSITORY = Symbol('PUBLIC_PAGE_REPOSITORY');
export const SITE_REPOSITORY = Symbol('PUBLIC_SITE_REPOSITORY');
export const SITE_LAYOUT_SECTION_REPOSITORY = Symbol(
  'PUBLIC_SITE_LAYOUT_SECTION_REPOSITORY',
);
export const SEARCH_REPOSITORY = Symbol('PUBLIC_SEARCH_REPOSITORY');
export const DEFAULT_TENANT_ID = Symbol('PUBLIC_DEFAULT_TENANT_ID');
export const PREVIEW_TOKEN_PORT = Symbol('PUBLIC_PREVIEW_TOKEN_PORT');
