export const TAXONOMY_REPOSITORY = Symbol('TAXONOMY_REPOSITORY');
export const PAGE_TRANSLATION_REPOSITORY = Symbol(
  'PAGE_TRANSLATION_REPOSITORY',
);
export const SITE_REPOSITORY = Symbol('SITE_REPOSITORY');
